# Generated by Django 2.2.7 on 2020-02-26 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('dept_id', models.CharField(max_length=12)),
                ('hod', models.CharField(max_length=22)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('bvn', models.CharField(max_length=11)),
                ('lga', models.CharField(max_length=20)),
                ('nimc', models.CharField(max_length=11, unique=True)),
                ('address', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=25)),
                ('first_name', models.CharField(max_length=25)),
                ('bank_name', models.CharField(max_length=50)),
                ('account_name', models.CharField(max_length=100)),
                ('disability', models.CharField(blank=True, max_length=150, null=True)),
                ('other_name', models.CharField(blank=True, max_length=25, null=True)),
                ('next_of_kin', models.CharField(max_length=25)),
                ('nationality', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=30)),
                ('salary_amount', models.IntegerField(default=0)),
                ('place_of_work', models.CharField(max_length=25)),
                ('account_number', models.CharField(max_length=10)),
                ('state_of_origin', models.CharField(max_length=20)),
                ('passport', models.ImageField(upload_to='passports/')),
                ('fingerprint', models.CharField(max_length=48)),
                ('date_of_birth', models.DateTimeField()),
                ('date_of_employment', models.DateTimeField()),
                ('date_of_retirement', models.DateTimeField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=7)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wisapp.Department')),
            ],
        ),
    ]
